xxl:
  job:
    accessToken: ''
    admin.addresses: http://@package.host@:8180/xxl-job-admin
    #admin.addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: jwolf-manager
      address: ''
      ip: ''
      port: 9993
      logpath: /var/log/jwolf/xxl-jobhandler
      logretentiondays: 5

server:
  port: 8888
  servlet:
    context-path: /jwolf/manage
spring:
  profiles:
    active: test


---
server:
  servlet:
    session:
      cookie:
        # 防止cookie冲突，冲突会导致登录验证不通过，如果不同client端使用相同的cookie名会导致挤掉另一client授权的cookie被覆盖
        name: OAUTH2-CLIENT1-SESSIONID
oauth2-service-url: http://localhost:9402
security:
  oauth2:
    client:
      client-id: client1
      client-secret: secret1
      user-authorization-uri: ${oauth2-service-url}/oauth/authorize
      access-token-uri: ${oauth2-service-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-service-url}/oauth/token_key
        key-value: dev #对应认证服务器jwt key的签名
    sso:
      login-path: /me #自动拼接server.servlet.context-path
