
xxl:
  job:
    accessToken: ''
    admin.addresses: http://@package.host@:8180/xxl-job-admin
    #admin.addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: jwolf-manager
      address: ''
      ip: ''
      port: 9993
      logpath: /var/log/jwolf/xxl-jobhandler
      logretentiondays: 5
server:
  port: 8888
  servlet:
    context-path: /jwolf/manage
spring:
  profiles:
    active: test
  application:
    name: manage
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  #redis配置
  redis:
    host: @package.host@
    port: 6379
    #password: 123456
    timeout: 2000
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制
        max-active: 10
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


---
server:
  servlet:
    session:
      cookie:
        # 防止cookie冲突，冲突会导致登录验证不通过，如果不同client端使用相同的cookie名会导致挤掉另一client授权的cookie被覆盖
        name: OAUTH2-CLIENT1-SESSIONID
        path: /
oauth2-service-url: http://@package.host@:9402
security:
  oauth2:
    client:
      client-id: client1
      client-secret: secret1
      user-authorization-uri: ${oauth2-service-url}/oauth/authorize
      access-token-uri: ${oauth2-service-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-service-url}/oauth/token_key
        key-value: dev #对应认证服务器jwt key的签名
    sso:
      login-path: /login #自动拼接server.servlet.context-path,暂未使用
