#连接池配置详见https://blog.csdn.net/MyHerux/article/details/80730690
spring:
  datasource:
    name: user
    url: jdbc:mysql://192.168.154.137:3306/jwolf_user?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

  #redis配置
  redis:
    host: 192.168.154.137
    port: 6379
    #password: 123456
    timeout: 2000
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制
        max-active: 10
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


