global:
  scrape_timeout: 10s   # scrape_timeout is set to the global default (10s).
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Alertmanager configuration
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
#       - alertmanager:9093
#    timeout: 10s
# 报警配置
#报警原理：周期性拉取到指标后评估如果满足规则文件里的触发条件并且保持到指定的“for时间”，报警状态由inactive=>pending=>firing，
#通过配置的alertmanager URL发送http请求给alertmanager，alertmanager收到一个alert并根据alertmanager.yml配置的邮件或webhook丁丁微信等及rules报警
#rule_files:
#  - '/etc/prometheus/alert.yml'  #挂载到容器内的路径

#抓取配置
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics' #默认
    scheme: 'http'  #默认
#    scrape_interval: 10s    #覆盖全局
#    static_configs:
#    - targets: ['localhost:9090']
#      labels:
#        instance: xxx
#安装参考后面的node-exporter
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['localhost:9100']
#  - job_name: 'cadvisor'
#    static_configs:
#    - targets: ['localhost:9111']
  - job_name: "jwolf-service-user"
    metrics_path: "/actuator/prometheus"
    static_configs:
    - targets: ["localhost:8880"]