apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-es.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-es.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/esnet: "true"
        io.kompose.service: kibana
    spec:
      containers:
        - env:
            - name: elasticsearch.hosts
              value: ' [ "http://elasticsearch:9200" ]'
            - name: i18n.locale
              value: zh-CN
            - name: server.host
              value: 0.0.0.0
            - name: xpack.monitoring.ui.container.elasticsearch.enabled
              value: "true"
          image: kibana:7.14.2
          name: kibana
          ports:
            - containerPort: 5601
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/kibana/plugins
              name: kibana-claim0
            - mountPath: /usr/share/kibana/config/kibana.yml
              name: kibana-claim1
      restartPolicy: Always
      volumes:
        - name: kibana-claim0
          persistentVolumeClaim:
            claimName: kibana-claim0
        - name: kibana-claim1
          persistentVolumeClaim:
            claimName: kibana-claim1
status: {}
