apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-extra.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  containers:
    - env:
        - name: MONGO_DATA_DIR
          value: /data/db
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "123456"
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_LOG_DIR
          value: /data/logs
      image: mongo:4.1.2
      name: mongodb
      ports:
        - containerPort: 27017
      resources: {}
      volumeMounts:
        - mountPath: /data/db
          name: mongodb-claim0
        - mountPath: /data/logs
          name: mongodb-claim1
  restartPolicy: OnFailure
  volumes:
    - name: mongodb-claim0
      persistentVolumeClaim:
        claimName: mongodb-claim0
    - name: mongodb-claim1
      persistentVolumeClaim:
        claimName: mongodb-claim1
status: {}
