apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-extra.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: rmqbroker
  name: rmqbroker
spec:
  ports:
    - name: "10909"
      port: 10909
      targetPort: 10909
    - name: "10911"
      port: 10911
      targetPort: 10911
  selector:
    io.kompose.service: rmqbroker
status:
  loadBalancer: {}
