apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-extra.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: rmqconsole
  name: rmqconsole
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 8080
  selector:
    io.kompose.service: rmqconsole
status:
  loadBalancer: {}
