apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-extra.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.network/jwolf: "true"
    io.kompose.service: rmqnamesrv
  name: rmqnamesrv
spec:
  containers:
    - image: foxiswho/rocketmq:server
      name: rmqnamesrv
      ports:
        - containerPort: 9876
      resources: {}
      volumeMounts:
        - mountPath: /opt/logs
          name: rmqnamesrv-claim0
        - mountPath: /opt/store
          name: rmqnamesrv-claim1
  restartPolicy: OnFailure
  volumes:
    - name: rmqnamesrv-claim0
      persistentVolumeClaim:
        claimName: rmqnamesrv-claim0
    - name: rmqnamesrv-claim1
      persistentVolumeClaim:
        claimName: rmqnamesrv-claim1
status: {}
