apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-base.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.network/jwolf: "true"
    io.kompose.service: sentinel
  name: sentinel
spec:
  containers:
    - image: bladex/sentinel-dashboard
      name: sentinel
      ports:
        - containerPort: 8719
        - containerPort: 8858
      resources: {}
  restartPolicy: OnFailure
status: {}
