apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-base.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sentinel
  name: sentinel
spec:
  ports:
    - name: "8719"
      port: 8719
      targetPort: 8719
    - name: "8858"
      port: 8858
      targetPort: 8858
  selector:
    io.kompose.service: sentinel
status:
  loadBalancer: {}
