apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-base.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: xxl-job-admin
  name: xxl-job-admin
spec:
  ports:
    - name: "8180"
      port: 8180
      targetPort: 8080
  selector:
    io.kompose.service: xxl-job-admin
status:
  loadBalancer: {}
