apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64-1.exe -f docker-compose-base.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.network/jwolf: "true"
    io.kompose.service: xxl-job-admin
  name: xxl-job-admin
spec:
  containers:
    - env:
        - name: PARAMS
          value: --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root  --spring.datasource.password=123456 --xxl.job.login.username=admin  --xxl.job.login.password=123456
      image: xuxueli/xxl-job-admin:2.3.0
      name: xxl-job-admin
      ports:
        - containerPort: 8080
      resources: {}
      volumeMounts:
        - mountPath: /data/applogs
          name: xxl-job-admin-claim0
  restartPolicy: OnFailure
  volumes:
    - name: xxl-job-admin-claim0
      persistentVolumeClaim:
        claimName: xxl-job-admin-claim0
status: {}
