#
version: "3.2"
services:

  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    restart: on-failure
    networks:
      - jwolf
    ports:
      - '2182:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    container_name: kafka
    user: root
    restart: always
    networks:
      - jwolf
    ports:
      - 9092:9092
    volumes:
      - /etc/kafka/config:/opt/bitnami/kafka/config
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: on-failure
    ports:
      - '8280:8080'
      - '50000:50000'
    volumes:
      - '/home/data/jenkins_home:/var/jenkins_home'
    networks:
      - jwolf

networks:
  jwolf:
    driver: bridge

