#
version: "3.2"
services:

  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    restart: on-failure
    networks:
      - jwolf
    ports:
      - '2182:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  #启动失败？删除data/meta.properties
  kafka:
    image: bitnami/kafka:2.6.0
    container_name: kafka
    user: root
    restart: always
    networks:
      - jwolf
    ports:
      - 9092:9092
    volumes:
      - /home/data/kafka:/bitnami/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.154.140:9092  #！！！！向外部暴露的地址！！！,即client端连接需走这个地址
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


  mongodb:
      image: mongo:4.1.2
      container_name: mongodb
      restart: on-failure
      environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/data/logs
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=123456
      volumes:
          - /home/data/mongodb:/data/db
          - /var/log/mongodb:/data/logs
      ports:
          - 27017:27017

  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: on-failure
    ports:
      - '8280:8080'
      - '50000:50000'
    volumes:
      - '/home/data/jenkins_home:/var/jenkins_home'
    networks:
      - jwolf

networks:
  jwolf:
    driver: bridge

