server:
  port: 9402
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  redis:
    host: 192.168.154.140
    port: 6379
    #password: 123456
    timeout: 2000
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制
        max-active: 10
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
security:
  oauth2:
    sso:
      login-path: /mylogin  #默认走框架内部的 /login,不好看

