#0. kubectl create namespace jwolf
#1.先创建configmap: kubectl create configmap redis-configmap --from-file=/etc/redis/redis.conf -n jwolf
#2.创建：kubectl apply -f redis-deployment.yml ，按文件删除资源：kubectl delete -f redis-deployment.ym
#3.查看各资源状态：kubectl get all --all-namespaces -o wide


kind: Service
apiVersion: v1
metadata:
  labels:
    name: mysql
  name: mysql
  namespace: jwolf    #使用自定义namespace
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    name: mysql

---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: mysql
  name: mysqlNodePort
  namespace: jwolf    #使用自定义namespace
spec:
  type: NodePort
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 3306
  selector:
    name: mysql

---

apiVersion: apps/v1  #注意v1版本不支持Deployment
kind: Deployment
metadata:
  name: mysql
  namespace: jwolf    #使用自定义namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
         name: mysql
    spec:
      nodeSelector:
        mynodelable: node1
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_PASSWORD
              value: "123456"
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_USER
              value: test
          image: mysql:8
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql

          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-claim0
            - mountPath: /var/log/mysqld.log
              name: mysql-claim1
            - mountPath: /var/lib/mysql-files
              name: mysql-claim2
            - mountPath: /etc/localtime
              name: mysql-claim3
            - mountPath: /etc/mysql/my.cnf
              name: mysql-claim4
      restartPolicy: Always
      volumes:
        - name: mysql-claim0
          hostPath:
            path: /home/data/mysql
        - name: mysql-claim1
          hostPath:
            path: /var/log/mysqld.log
        - name: mysql-claim2
          hostPath:
            path: /var/lib/mysql-files
        - name: mysql-claim3
          hostPath:
            path: /etc/localtime
        - name: mysql-claim4
          hostPath:
            path: /etc/my.cnf





