apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jwolf
  name: redis-datadir-pv-1
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.18
    path: /home/data/k8s-data/redis/datadir-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-datadir-pvc-1
  namespace: jwolf
spec:
  accessModes:
    - ReadWriteMany
  volumeName: redis-datadir-pv-1
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jwolf
  name: redis-datadir-pv-2
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.18
    path: /home/data/k8s-data/redis/datadir-pv-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-datadir-pvc-2
  namespace: jwolf
spec:
  accessModes:
    - ReadWriteMany
  volumeName: redis-datadir-pv-2
  resources:
    requests:
      storage: 2Gi