#连接池配置详见https://blog.csdn.net/MyHerux/article/details/80730690
spring:
  datasource:
    name: prod
    url: jdbc:mysql://127.0.0.1:3306/vehicle_v2?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 2000
    database: 15
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 10
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms







