#spring:
#  servlet:
#    multipart:
#      max-file-size: 10MB
#
#  jackson:
#    time-zone: GMT+8
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: false # 开启从注册中心动态创建路由的功能，利用微服务名进行路由,uri即可支持lb://微服务名进行负载均衡调用
#      routes:
#      - id: goods
#        uri: lb://goods
#        predicates:
#        - Path=/jwolf/goods/**
#        filters:
#        - StripPrefix=1
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 1
#            key-resolver: '#{@apiKeyResolver}'
#server:
#  port: 8880